### ISSUE TITLE
Distribute binaries

### ISSUE THREAD

**Issue by Blaisorblade** [facebookarchive/nailgun#32]
Hi,
I'm using nailgun for a small nice project (https://github.com/Blaisorblade/filter-branch-msgs), it was a breeze to do. However, I have Windows friends who need this, and I'd like to point them to an easy install procedure.
Right now, I've added a link [to the binaries from `zinc`](https://github.com/typesafehub/zinc/tree/master/dist/src/dist/bin/ng), but that seems slightly silly. Could you provide at least Windows binaries?

Thanks,
Paolo

**Comment by jason-sachs** [comment]
+1

**Comment by BenjaminSchiborr** [comment]
+1
