### ISSUE TITLE
Prefer better build system instead? 230 s (4 minutes) for a fresh build is unacceptable.

### ISSUE THREAD

**Issue by gorakhargosh** [facebookarchive/nailgun#53]
Fresh build times:

third_party/java/nailgun$ time mvn package
230.53 real 20.14 user 2.54 sys
third_party/java/nailgun$ tup
... elided ...
[2.297s] third_party/java/nailgun/nailgun-server: [JAVAC_JAR] nailgun-server.jar
... elided ...

230 seconds is about 4 minutes! Versus 2.2 seconds. You don't have a ton of dependencies
with nailgun. Please drop Maven and consider using a real build system: 
https://github.com/facebook/buck or http://gittup.org/tup/.

**Comment by andrewgaul** [comment]
@gorakhargosh I cannot reproduce your symptoms on a modest laptop:

```
$ time mvn clean package --quiet

real    0m7.522s
user    0m21.911s
sys     0m0.856s
```

**Comment by jvican** [comment]
Can we close?
